version: '3.8'

services:
  backend:
    build: backend
    volumes:
      - ./backend:/usr/src/app/
      - ./backend:/code
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    image: node:10.15.1
    command: npm run docker
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    env_file:
      - ./frontend/.env
    environment:
      HOST: 0.0.0.0
    ports:
      - "3000:3000"

  db:
    image: postgres:13.0-alpine
    volumes:
      - ./db:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env

  server:
    image: node:10.15.1
    command: npm run docker
    working_dir: /usr/src/app
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - frontend
    ports:
      - "4000:4000"

volumes:
  postgres_data: