version: '3.9'

services:
  backend:
    container_name: backend_service
    build: backend
    volumes:
      - ./backend:/usr/src/app/
      - ./backend:/code
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    container_name: frontend_service
    image: node:14.18-stretch-slim
    command: npm run docker
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    env_file:
      - ./frontend/.env
    environment:
      HOST: 0.0.0.0
    ports:
      - "3000:3000"

  server:
    container_name: server_service
    image: node:14.18-stretch-slim
    command: npm run docker
    working_dir: /usr/src/app
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - frontend
    ports:
      - "4000:4000"

  db:
    container_name: db_service
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    restart: always

volumes:
  postgres_data:
    driver: local
